// <auto-generated />
using System;
using AccServerAdmin.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccServerAdmin.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210209113554_SQlServer Initial Create")]
    partial class SQlServerInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.AssistRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DisableAutoClutch")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutoEngineStart")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutoGear")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutoLights")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutoPitLimiter")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutoWiper")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableAutosteer")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableIdealLine")
                        .HasColumnType("bit");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StabilityControlLevelMax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("AssistRules");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.BalanceOfPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ballast")
                        .HasColumnType("int");

                    b.Property<int>("Car")
                        .HasColumnType("int");

                    b.Property<int>("Restrictor")
                        .HasColumnType("int");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("BalanceOfPerformance");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AiAggro")
                        .HasColumnType("int");

                    b.Property<int>("AiConsistency")
                        .HasColumnType("int");

                    b.Property<int>("AiRainSkill")
                        .HasColumnType("int");

                    b.Property<int>("AiSkill")
                        .HasColumnType("int");

                    b.Property<int>("DriverCategory")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlovesTemplateKey")
                        .HasColumnType("int");

                    b.Property<int>("HelmetBaseColor")
                        .HasColumnType("int");

                    b.Property<int>("HelmetDetailColor")
                        .HasColumnType("int");

                    b.Property<int>("HelmetGlassColor")
                        .HasColumnType("int");

                    b.Property<double>("HelmetGlassMetallic")
                        .HasColumnType("float");

                    b.Property<int>("HelmetMaterialType")
                        .HasColumnType("int");

                    b.Property<int>("HelmetTemplateKey")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Shortname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuitDetailColor1")
                        .HasColumnType("int");

                    b.Property<int>("SuitDetailColor2")
                        .HasColumnType("int");

                    b.Property<int>("SuitTemplateKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.DriverEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.HasKey("EntryId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverEntries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ballast")
                        .HasColumnType("int");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<string>("CustomCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultGridPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("EntryListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ForcedCarModel")
                        .HasColumnType("int");

                    b.Property<Guid?>("GlobalEntryListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OverrideCarModelForCustomCar")
                        .HasColumnType("bit");

                    b.Property<bool>("OverrideDriverInfo")
                        .HasColumnType("bit");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("int");

                    b.Property<int>("Restrictor")
                        .HasColumnType("int");

                    b.Property<bool>("ServerAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntryListId");

                    b.HasIndex("GlobalEntryListId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EntryList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<bool>("ForceEntryList")
                        .HasColumnType("bit");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("EntryList");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EventCfg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmbientTemp")
                        .HasColumnType("int");

                    b.Property<double>("CloudLevel")
                        .HasColumnType("float");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostQualySeconds")
                        .HasColumnType("int");

                    b.Property<int>("PostRaceSeconds")
                        .HasColumnType("int");

                    b.Property<int>("PreRaceWaitingTimeSeconds")
                        .HasColumnType("int");

                    b.Property<double>("Rain")
                        .HasColumnType("float");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SessionOverTimeSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("SimRacerWeatherConditions")
                        .HasColumnType("bit");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("WeatherRandomness")
                        .HasColumnType("int");

                    b.Property<bool>("isFixedConditionQualification")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("EventCfgs");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EventRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverStintTime")
                        .HasColumnType("int");

                    b.Property<int>("MandatoryPitstopCount")
                        .HasColumnType("int");

                    b.Property<bool>("MandatoryPitstopRefuellingRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("MandatoryPitstopSwapDriverRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("MandatoryPitstopTyreChangeRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDriversCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotalDrivingTime")
                        .HasColumnType("int");

                    b.Property<int>("PitWindowLength")
                        .HasColumnType("int");

                    b.Property<int>("QualifyType")
                        .HasColumnType("int");

                    b.Property<bool>("RefuellingAllowedInRace")
                        .HasColumnType("bit");

                    b.Property<bool>("RefuellingTimeFixed")
                        .HasColumnType("bit");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TyreSetCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("EventRules");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.GameCfg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowAutoDisqualification")
                        .HasColumnType("bit");

                    b.Property<int>("CarGroup")
                        .HasColumnType("int");

                    b.Property<string>("CentralEntryListPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DumpEntryList")
                        .HasColumnType("bit");

                    b.Property<bool>("DumpLeaderboards")
                        .HasColumnType("bit");

                    b.Property<int>("FormationLap")
                        .HasColumnType("int");

                    b.Property<bool>("IsRaceLocked")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCarSlots")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacecraftRatingRequirement")
                        .HasColumnType("int");

                    b.Property<bool>("RandomizeTrackWhenEmpty")
                        .HasColumnType("bit");

                    b.Property<int>("SafetyRatingRequirement")
                        .HasColumnType("int");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShortFormationLap")
                        .HasColumnType("bit");

                    b.Property<string>("SpectatorPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackMedalsRequirement")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("GameCfgs");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.NetworkCfg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("int");

                    b.Property<bool>("RegisterToLobby")
                        .HasColumnType("bit");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TcpPort")
                        .HasColumnType("int");

                    b.Property<int>("UdpPort")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("NetworkCfgs");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.SessionConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeekend")
                        .HasColumnType("int");

                    b.Property<Guid>("EventCfgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("int");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SessionType")
                        .HasColumnType("int");

                    b.Property<int>("TimeMultiplier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventCfgId");

                    b.ToTable("SessionConfiguration");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminPassphrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceBasePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerBasePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.GlobalEntryList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("GlobalEntries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.LeaderboardLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BestLap")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit1")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit2")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit3")
                        .HasColumnType("int");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentDriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LapCount")
                        .HasColumnType("int");

                    b.Property<int>("LastLap")
                        .HasColumnType("int");

                    b.Property<int>("LastSplit1")
                        .HasColumnType("int");

                    b.Property<int>("LastSplit2")
                        .HasColumnType("int");

                    b.Property<int>("LastSplit3")
                        .HasColumnType("int");

                    b.Property<bool>("MissingMandatoryPitstop")
                        .HasColumnType("bit");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CurrentDriverId");

                    b.HasIndex("SessionId");

                    b.ToTable("LeaderboardLines");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BestLap")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit1")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit2")
                        .HasColumnType("int");

                    b.Property<int>("BestSplit3")
                        .HasColumnType("int");

                    b.Property<bool>("IsWet")
                        .HasColumnType("bit");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SessionTimestamp")
                        .IsUnique();

                    b.HasIndex("Track");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarModel")
                        .HasColumnType("int");

                    b.Property<long>("CupCategory")
                        .HasColumnType("bigint");

                    b.Property<long>("RaceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SessionCars");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionCarDriver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionCarId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverId", "SessionCarId");

                    b.HasIndex("SessionCarId");

                    b.ToTable("SessionCarDrivers");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionLap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Lap")
                        .HasColumnType("int");

                    b.Property<long>("LapTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Split1")
                        .HasColumnType("bigint");

                    b.Property<long>("Split2")
                        .HasColumnType("bigint");

                    b.Property<long>("Split3")
                        .HasColumnType("bigint");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionLaps");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionPenalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClearedInLap")
                        .HasColumnType("int");

                    b.Property<string>("Penalty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PenaltyValue")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViolationInLap")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionPenalties");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CollectResults")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.AssistRules", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("AssistRules")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.AssistRules", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.BalanceOfPerformance", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithMany("ServerBop")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Driver", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.AccConfig.Entry", null)
                        .WithMany("Drivers")
                        .HasForeignKey("EntryId");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.DriverEntry", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.AccConfig.Driver", "Driver")
                        .WithMany("Entries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccServerAdmin.Domain.AccConfig.Entry", "Entry")
                        .WithMany("Entries")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Entry", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.AccConfig.EntryList", null)
                        .WithMany("Entries")
                        .HasForeignKey("EntryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccServerAdmin.Domain.GlobalEntryList", null)
                        .WithMany("Entries")
                        .HasForeignKey("GlobalEntryListId");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EntryList", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("EntryList")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.EntryList", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EventCfg", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("EventCfg")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.EventCfg", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EventRules", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("EventRules")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.EventRules", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.GameCfg", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("GameCfg")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.GameCfg", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.NetworkCfg", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Server", null)
                        .WithOne("NetworkCfg")
                        .HasForeignKey("AccServerAdmin.Domain.AccConfig.NetworkCfg", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.SessionConfiguration", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.AccConfig.EventCfg", null)
                        .WithMany("Sessions")
                        .HasForeignKey("EventCfgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.LeaderboardLine", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Results.SessionCar", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("AccServerAdmin.Domain.AccConfig.Driver", "CurrentDriver")
                        .WithMany()
                        .HasForeignKey("CurrentDriverId");

                    b.HasOne("AccServerAdmin.Domain.Results.Session", null)
                        .WithMany("LeaderBoard")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CurrentDriver");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionCarDriver", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.AccConfig.Driver", "Driver")
                        .WithMany("SessionCars")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccServerAdmin.Domain.Results.SessionCar", "Car")
                        .WithMany("Drivers")
                        .HasForeignKey("SessionCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionLap", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Results.SessionCar", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("AccServerAdmin.Domain.AccConfig.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("AccServerAdmin.Domain.Results.Session", null)
                        .WithMany("Laps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionPenalty", b =>
                {
                    b.HasOne("AccServerAdmin.Domain.Results.SessionCar", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("AccServerAdmin.Domain.Results.Session", null)
                        .WithMany("Penalties")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Driver", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("SessionCars");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.Entry", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EntryList", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.AccConfig.EventCfg", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.GlobalEntryList", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.Session", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("LeaderBoard");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Results.SessionCar", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("AccServerAdmin.Domain.Server", b =>
                {
                    b.Navigation("AssistRules");

                    b.Navigation("EntryList");

                    b.Navigation("EventCfg");

                    b.Navigation("EventRules");

                    b.Navigation("GameCfg");

                    b.Navigation("NetworkCfg");

                    b.Navigation("ServerBop");
                });
#pragma warning restore 612, 618
        }
    }
}
